### PR TITLE
Add support for re-usable containers

### PR DESCRIPTION
**Pull request by devuo**
Add support for developers to pass `gnomock.WithContainerReuse()` option that makes Gnomock attempt to re-use an already running container with the name specified via `gnomock.WithContainerName()`.

If the container with the given name does not exist, or if it uses a different image than the one configured, the normal flow of Gnomock is used, namely a new container is created in case it doesn't exist, or replaced if using a different image.

Pending:
- [x] Agree on technical solution
- [x] Add inline comments
- [x] Write tests

### CODE REVIEW

**Comment by devuo** [comment]
Related with https://github.com/orlangure/gnomock/pull/693

**Comment by devuo** [comment]
@orlangure tried to reproduce the problem but was unable to. For two reasons:

- The first is that the containers Gnomock creates have auto remove, then once they exit they are removed: https://github.com/orlangure/gnomock/blob/5e86a8bdd91b2c173a38ea445dbce89d543363a4/docker.go#L302
- The second because Gnomock is already handling the case of duplicate containers: https://github.com/orlangure/gnomock/blob/5e86a8bdd91b2c173a38ea445dbce89d543363a4/docker.go#L312-L324

**Comment by devuo** [comment]
@orlangure also added tests. The only test I did not add was for the "replacement scenario" (the one where the image mismatches) and that was because I didn't knew which image to use other than `docker.io/orlangure/gnomock-test-image`.

**Comment by orlangure** [comment]
@devuo, thank you so much for working on it, and for the last sidecar touch as well 😼
I'm a bit short on time to prepare a new release, and will try to work on in ASAP, maybe tonight or during the weekend.

**Review by orlangure — APPROVED** [review]
Perfect 😼
Thank you.

**Pull request merged**
