### PR TITLE
Upgrade Kafka Preset to 3.3.1-L0 with ARM 64 Support

### PR DESCRIPTION
**Pull request by rajatvig**

### CODE REVIEW

**Comment by rajatvig** [comment]
@orlangure Would I be right in assuming that the changes would work? Is there something else I need to change?

**Comment by orlangure** [comment]
Hey @rajatvig, thank you for working on this!

Yes, you can assume everything works. The build passes on amd64 instances, and I tested locally on arm64. I'll prepare a new release a little later, thanks!

**Review by orlangure — APPROVED** [review]

**Comment by rajatvig** [comment]
@orlangure Could you please consider merging it?

**Comment by orlangure** [comment]
Sorry for the delay, I'm planning to prepare a release this weekend. Merged for now 😻

**Pull request merged**
