### PR TITLE
WIP:Improve CircleCI builds

### LINKED ISSUE #74: Improve CircleCI builds (align with Github Actions)
CircleCI builds: https://app.circleci.com/pipelines/github/orlangure/gnomock
CircleCI workflow configuration: https://github.com/orlangure/gnomock/blob/master/.circleci/config.yml

Github Actions configuration: https://github.com/orlangure/gnomock/blob/master/.github/workflows/test.yaml

## 
Github Actions is the primary CI platform of this project. But many use CircleCI, and up until now Gnomock didn't work (at least sometimes) there.

Since we used Github Actions for project builds, we kind of constantly verified that Gnomock worked in this environment. So, to ensure that Gnomock also works in CircleCI, the best way would to have similar workflows in all supported platforms.

The goal of this task is to have all presets, core functionality, and SDKs (currently only python) tested in CircleCI builds, just like we have in Github Actions. The separation of jobs does not have to be the same, but it would be better if builds were relatively fast.

### PR DESCRIPTION
**Pull request by 0b01001110**
fixes #74

### CODE REVIEW

**Comment by orlangure** [comment]
Hi @0b01001110,
Amazing work! I see this is marked as WIP, but looks like everything already works as expected. Do you think there is more work here?

**Comment by 0b01001110** [comment]
Hi @orlangure 

Circle CI takes considerably longer than GitHub Action because the free plan only allows up to four jobs to be run in parallel.
(GitHub Action takes 8 minutes, CircleCI takes 17 minutes.)

I was trying to find a solution but I couldn't.

**Comment by orlangure** [comment]
@0b01001110, 17 minutes is great! We'll have faster feedback from github actions, but circleci builds will prove that everything works properly on both platforms.
Would you mind posting a link to the latest circleci build?
Let's get this merged, it's looks fantastic😻

**Comment by 0b01001110** [comment]
@orlangure 
Here is the link to the latest circleci build: https://app.circleci.com/pipelines/github/0b01001110/gnomock/19/workflows/f0657d16-8bf4-440f-b181-20e1c09a7743

The build of the same commit succeeded first, but now only the test-sdk-python job fails. 🤕 

```
#!/bin/bash -eo pipefail
cd sdktest/python
python3 -m pytest -n 3 -v -k TestSDK

============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /opt/circleci/.pyenv/versions/3.6.9/bin/python3
cachedir: .pytest_cache
rootdir: /home/circleci/project/sdktest/python
plugins: xdist-1.31.0, forked-1.1.3
gw0 I / gw1 I / gw2 I[gw0] linux Python 3.6.9 cwd: /home/circleci/project/sdktest/python
gw0 C / gw1 I / gw2 I[gw1] linux Python 3.6.9 cwd: /home/circleci/project/sdktest/python
gw0 C / gw1 C / gw2 I[gw2] linux Python 3.6.9 cwd: /home/circleci/project/sdktest/python
gw0 C / gw1 C / gw2 C[gw1] Python 3.6.9 (default, Dec  4 2020, 04:40:22)  -- [GCC 4.8.4]
gw0 C / gw1 ok / gw2 C[gw0] Python 3.6.9 (default, Dec  4 2020, 04:40:22)  -- [GCC 4.8.4]
gw0 ok / gw1 ok / gw2 C[gw2] Python 3.6.9 (default, Dec  4 2020, 04:40:22)  -- [GCC 4.8.4]
gw0 ok / gw1 ok / gw2 okcollecting 0 items / 1 error                                                   collecting 0 items / 28 errors                                                 gw0 ok / gw1 [13] / gw2 okgw0 [13] / gw1 [13] / gw2 okgw0 [13] / gw1 [13] / gw2 [13]
scheduling tests via LoadScheduling

test/test_sdk.py::TestSDK::test_elastic 
test/test_sdk.py::TestSDK::test_kubernetes 
test/test_sdk.py::TestSDK::test_kafka 
[gw2] [  7%] FAILED test/test_sdk.py::TestSDK::test_kubernetes 
test/test_sdk.py::TestSDK::test_memcached 
[gw2] [ 15%] FAILED test/test_sdk.py::TestSDK::test_memcached 
[gw1] [ 23%] FAILED test/test_sdk.py::TestSDK::test_elastic 
test/test_sdk.py::TestSDK::test_mongo 
test/test_sdk.py::TestSDK::test_localstack 
[gw0] [ 30%] FAILED test/test_sdk.py::TestSDK::test_kafka 
test/test_sdk.py::TestSDK::test_mariadb 
[gw2] [ 38%] FAILED test/test_sdk.py::TestSDK::test_mongo 
test/test_sdk.py::TestSDK::test_mysql 
[gw1] [ 46%] FAILED test/test_sdk.py::TestSDK::test_localstack 
test/test_sdk.py::TestSDK::test_mssql 
[gw2] [ 53%] FAILED test/test_sdk.py::TestSDK::test_mysql 
[gw0] [ 61%] FAILED test/test_sdk.py::TestSDK::test_mariadb 
test/test_sdk.py::TestSDK::test_rabbitmq 
test/test_sdk.py::TestSDK::test_postgres 
[gw1] [ 69%] FAILED test/test_sdk.py::TestSDK::test_mssql 
[gw2] [ 76%] FAILED test/test_sdk.py::TestSDK::test_rabbitmq 
test/test_sdk.py::TestSDK::test_redis 
test/test_sdk.py::TestSDK::test_splunk 
[gw0] [ 84%] FAILED test/test_sdk.py::TestSDK::test_postgres 
[gw2] [ 92%] FAILED test/test_sdk.py::TestSDK::test_splunk 
[gw1] [100%] FAILED test/test_sdk.py::TestSDK::test_redis 

==================================== ERRORS ====================================
_______________ ERROR collecting gnomock/test/test_container.py ________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_container.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_container.py:17: in <module>
    from gnomock.model.named_ports import NamedPorts
gnomock/gnomock/model/named_ports.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
________________ ERROR collecting gnomock/test/test_elastic.py _________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_elastic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_elastic.py:17: in <module>
    from gnomock.model.elastic import Elastic
gnomock/gnomock/model/elastic.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
____________ ERROR collecting gnomock/test/test_elastic_request.py _____________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_elastic_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_elastic_request.py:17: in <module>
    from gnomock.model.elastic import Elastic
gnomock/gnomock/model/elastic.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_________ ERROR collecting gnomock/test/test_invalid_start_request.py __________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_invalid_start_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_invalid_start_request.py:17: in <module>
    from gnomock.model.invalid_start_request import InvalidStartRequest
gnomock/gnomock/model/invalid_start_request.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
__________ ERROR collecting gnomock/test/test_invalid_stop_request.py __________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_invalid_stop_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_invalid_stop_request.py:17: in <module>
    from gnomock.model.invalid_stop_request import InvalidStopRequest
gnomock/gnomock/model/invalid_stop_request.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_________________ ERROR collecting gnomock/test/test_kafka.py __________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_kafka.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_kafka.py:17: in <module>
    from gnomock.model.kafka_messages import KafkaMessages
gnomock/gnomock/model/kafka_messages.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_____________ ERROR collecting gnomock/test/test_kafka_messages.py _____________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_kafka_messages.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_kafka_messages.py:17: in <module>
    from gnomock.model.kafka_messages import KafkaMessages
gnomock/gnomock/model/kafka_messages.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_____________ ERROR collecting gnomock/test/test_kafka_request.py ______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_kafka_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_kafka_request.py:17: in <module>
    from gnomock.model.kafka import Kafka
gnomock/gnomock/model/kafka.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_______________ ERROR collecting gnomock/test/test_kubernetes.py _______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_kubernetes.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_kubernetes.py:17: in <module>
    from gnomock.model.kubernetes import Kubernetes
gnomock/gnomock/model/kubernetes.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
___________ ERROR collecting gnomock/test/test_kubernetes_request.py ___________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_kubernetes_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_kubernetes_request.py:17: in <module>
    from gnomock.model.kubernetes import Kubernetes
gnomock/gnomock/model/kubernetes.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_______________ ERROR collecting gnomock/test/test_localstack.py _______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_localstack.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_localstack.py:17: in <module>
    from gnomock.model.localstack import Localstack
gnomock/gnomock/model/localstack.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
___________ ERROR collecting gnomock/test/test_localstack_request.py ___________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_localstack_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_localstack_request.py:17: in <module>
    from gnomock.model.localstack import Localstack
gnomock/gnomock/model/localstack.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
________________ ERROR collecting gnomock/test/test_mariadb.py _________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_mariadb.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_mariadb.py:17: in <module>
    from gnomock.model.mariadb import Mariadb
gnomock/gnomock/model/mariadb.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
____________ ERROR collecting gnomock/test/test_mariadb_request.py _____________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_mariadb_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_mariadb_request.py:17: in <module>
    from gnomock.model.mariadb import Mariadb
gnomock/gnomock/model/mariadb.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_______________ ERROR collecting gnomock/test/test_memcached.py ________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_memcached.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_memcached.py:17: in <module>
    from gnomock.model.memcached import Memcached
gnomock/gnomock/model/memcached.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
___________ ERROR collecting gnomock/test/test_memcached_request.py ____________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_memcached_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_memcached_request.py:17: in <module>
    from gnomock.model.memcached import Memcached
gnomock/gnomock/model/memcached.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_________________ ERROR collecting gnomock/test/test_mongo.py __________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_mongo.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_mongo.py:17: in <module>
    from gnomock.model.mongo import Mongo
gnomock/gnomock/model/mongo.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_____________ ERROR collecting gnomock/test/test_mongo_request.py ______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_mongo_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_mongo_request.py:17: in <module>
    from gnomock.model.mongo import Mongo
gnomock/gnomock/model/mongo.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_________________ ERROR collecting gnomock/test/test_mssql.py __________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_mssql.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_mssql.py:17: in <module>
    from gnomock.model.mssql import Mssql
gnomock/gnomock/model/mssql.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_____________ ERROR collecting gnomock/test/test_mssql_request.py ______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_mssql_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_mssql_request.py:17: in <module>
    from gnomock.model.mssql import Mssql
gnomock/gnomock/model/mssql.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_________________ ERROR collecting gnomock/test/test_mysql.py __________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_mysql.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_mysql.py:17: in <module>
    from gnomock.model.mysql import Mysql
gnomock/gnomock/model/mysql.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_____________ ERROR collecting gnomock/test/test_mysql_request.py ______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_mysql_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_mysql_request.py:17: in <module>
    from gnomock.model.mysql import Mysql
gnomock/gnomock/model/mysql.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
______________ ERROR collecting gnomock/test/test_named_ports.py _______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_named_ports.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_named_ports.py:17: in <module>
    from gnomock.model.named_ports import NamedPorts
gnomock/gnomock/model/named_ports.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
________________ ERROR collecting gnomock/test/test_options.py _________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_options.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_options.py:17: in <module>
    from gnomock.model.options import Options
gnomock/gnomock/model/options.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
________________ ERROR collecting gnomock/test/test_postgres.py ________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_postgres.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_postgres.py:17: in <module>
    from gnomock.model.postgres import Postgres
gnomock/gnomock/model/postgres.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
____________ ERROR collecting gnomock/test/test_postgres_request.py ____________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_postgres_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_postgres_request.py:17: in <module>
    from gnomock.model.options import Options
gnomock/gnomock/model/options.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
______________ ERROR collecting gnomock/test/test_presets_api.py _______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_presets_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_presets_api.py:16: in <module>
    from gnomock.api.presets_api import PresetsApi  # noqa: E501
gnomock/gnomock/api/presets_api.py:26: in <module>
    from gnomock.model.container import Container
gnomock/gnomock/model/container.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
________________ ERROR collecting gnomock/test/test_rabbitmq.py ________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_rabbitmq.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_rabbitmq.py:17: in <module>
    from gnomock.model.rabbitmq_message import RabbitmqMessage
gnomock/gnomock/model/rabbitmq_message.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
____________ ERROR collecting gnomock/test/test_rabbitmq_message.py ____________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_rabbitmq_message.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_rabbitmq_message.py:17: in <module>
    from gnomock.model.rabbitmq_message import RabbitmqMessage
gnomock/gnomock/model/rabbitmq_message.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
____________ ERROR collecting gnomock/test/test_rabbitmq_request.py ____________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_rabbitmq_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_rabbitmq_request.py:17: in <module>
    from gnomock.model.options import Options
gnomock/gnomock/model/options.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_________________ ERROR collecting gnomock/test/test_redis.py __________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_redis.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_redis.py:17: in <module>
    from gnomock.model.redis import Redis
gnomock/gnomock/model/redis.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_____________ ERROR collecting gnomock/test/test_redis_request.py ______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_redis_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_redis_request.py:17: in <module>
    from gnomock.model.options import Options
gnomock/gnomock/model/options.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_________________ ERROR collecting gnomock/test/test_splunk.py _________________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_splunk.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_splunk.py:17: in <module>
    from gnomock.model.splunk_values import SplunkValues
gnomock/gnomock/model/splunk_values.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_____________ ERROR collecting gnomock/test/test_splunk_request.py _____________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_splunk_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_splunk_request.py:17: in <module>
    from gnomock.model.options import Options
gnomock/gnomock/model/options.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
_____________ ERROR collecting gnomock/test/test_splunk_values.py ______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_splunk_values.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_splunk_values.py:17: in <module>
    from gnomock.model.splunk_values import SplunkValues
gnomock/gnomock/model/splunk_values.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
______________ ERROR collecting gnomock/test/test_start_failed.py ______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_start_failed.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_start_failed.py:17: in <module>
    from gnomock.model.start_failed import StartFailed
gnomock/gnomock/model/start_failed.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
______________ ERROR collecting gnomock/test/test_stop_failed.py _______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_stop_failed.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_stop_failed.py:17: in <module>
    from gnomock.model.stop_failed import StopFailed
gnomock/gnomock/model/stop_failed.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
______________ ERROR collecting gnomock/test/test_stop_request.py ______________
ImportError while importing test module '/home/circleci/project/sdktest/python/gnomock/test/test_stop_request.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
gnomock/test/test_stop_request.py:17: in <module>
    from gnomock.model.stop_request import StopRequest
gnomock/gnomock/model/stop_request.py:16: in <module>
    import nulltype  # noqa: F401
E   ModuleNotFoundError: No module named 'nulltype'
=================================== FAILURES ===================================
___________________________ TestSDK.test_kubernetes ____________________________
[gw2] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_kubernetes>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
____________________________ TestSDK.test_memcached ____________________________
[gw2] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_memcached>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
_____________________________ TestSDK.test_elastic _____________________________
[gw1] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_elastic>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
______________________________ TestSDK.test_kafka ______________________________
[gw0] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_kafka>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
______________________________ TestSDK.test_mongo ______________________________
[gw2] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_mongo>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
___________________________ TestSDK.test_localstack ____________________________
[gw1] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_localstack>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
______________________________ TestSDK.test_mysql ______________________________
[gw2] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_mysql>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
_____________________________ TestSDK.test_mariadb _____________________________
[gw0] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_mariadb>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
______________________________ TestSDK.test_mssql ______________________________
[gw1] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_mssql>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
____________________________ TestSDK.test_rabbitmq _____________________________
[gw2] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_rabbitmq>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
____________________________ TestSDK.test_postgres _____________________________
[gw0] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_postgres>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
_____________________________ TestSDK.test_splunk ______________________________
[gw2] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_splunk>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
______________________________ TestSDK.test_redis ______________________________
[gw1] linux -- Python 3.6.9 /opt/circleci/.pyenv/versions/3.6.9/bin/python3

self = <test_sdk.TestSDK testMethod=test_redis>

    def setUp(self):
        with gnomock.ApiClient() as client:
>           self.api = gnomock.PresetsApi(client)
E           AttributeError: module 'gnomock' has no attribute 'PresetsApi'

test/test_sdk.py:10: AttributeError
=========================== short test summary info ============================
FAILED test/test_sdk.py::TestSDK::test_kubernetes - AttributeError: module 'g...
FAILED test/test_sdk.py::TestSDK::test_memcached - AttributeError: module 'gn...
FAILED test/test_sdk.py::TestSDK::test_elastic - AttributeError: module 'gnom...
FAILED test/test_sdk.py::TestSDK::test_kafka - AttributeError: module 'gnomoc...
FAILED test/test_sdk.py::TestSDK::test_mongo - AttributeError: module 'gnomoc...
FAILED test/test_sdk.py::TestSDK::test_localstack - AttributeError: module 'g...
FAILED test/test_sdk.py::TestSDK::test_mysql - AttributeError: module 'gnomoc...
FAILED test/test_sdk.py::TestSDK::test_mariadb - AttributeError: module 'gnom...
FAILED test/test_sdk.py::TestSDK::test_mssql - AttributeError: module 'gnomoc...
FAILED test/test_sdk.py::TestSDK::test_rabbitmq - AttributeError: module 'gno...
FAILED test/test_sdk.py::TestSDK::test_postgres - AttributeError: module 'gno...
FAILED test/test_sdk.py::TestSDK::test_splunk - AttributeError: module 'gnomo...
FAILED test/test_sdk.py::TestSDK::test_redis - AttributeError: module 'gnomoc...
ERROR gnomock/test/test_container.py
ERROR gnomock/test/test_elastic.py
ERROR gnomock/test/test_elastic_request.py
ERROR gnomock/test/test_invalid_start_request.py
ERROR gnomock/test/test_invalid_stop_request.py
ERROR gnomock/test/test_kafka.py
ERROR gnomock/test/test_kafka_messages.py
ERROR gnomock/test/test_kafka_request.py
ERROR gnomock/test/test_kubernetes.py
ERROR gnomock/test/test_kubernetes_request.py
ERROR gnomock/test/test_localstack.py
ERROR gnomock/test/test_localstack_request.py
ERROR gnomock/test/test_mariadb.py
ERROR gnomock/test/test_mariadb_request.py
ERROR gnomock/test/test_memcached.py
ERROR gnomock/test/test_memcached_request.py
ERROR gnomock/test/test_mongo.py
ERROR gnomock/test/test_mongo_request.py
ERROR gnomock/test/test_mssql.py
ERROR gnomock/test/test_mssql_request.py
ERROR gnomock/test/test_mysql.py
ERROR gnomock/test/test_mysql_request.py
ERROR gnomock/test/test_named_ports.py
ERROR gnomock/test/test_options.py
ERROR gnomock/test/test_postgres.py
ERROR gnomock/test/test_postgres_request.py
ERROR gnomock/test/test_presets_api.py
ERROR gnomock/test/test_rabbitmq.py
ERROR gnomock/test/test_rabbitmq_message.py
ERROR gnomock/test/test_rabbitmq_request.py
ERROR gnomock/test/test_redis.py
ERROR gnomock/test/test_redis_request.py
ERROR gnomock/test/test_splunk.py
ERROR gnomock/test/test_splunk_request.py
ERROR gnomock/test/test_splunk_values.py
ERROR gnomock/test/test_start_failed.py
ERROR gnomock/test/test_stop_failed.py
ERROR gnomock/test/test_stop_request.py
======================== 13 failed, 38 errors in 2.51s =========================

Exited with code exit status 1
CircleCI received exit code 1
```

I'm not familiar with Python, so it might take some time. 
If you know how to solve this error, I would appreciate it if you could let me know.

Thank you,

**Comment by orlangure** [comment]
Hi, @0b01001110,

It was my bad: each build pulled the `latest` generator image, which apparently introduced some breaking changes. I locked down the image to `v4.3.1`, and executed your circleci build with updated code. Everything worked perfectly😼

This is a very important addition to our CI pipeline, now gnomock will be available to circleci users, and this build could be used as an example. Thanks for working on it!

Before we merge it, would you mind updating from `master` and squashing into a single commit with a message like `Add CircleCI test pipeline`?

**Review by orlangure — APPROVED** [review]
Amazing job😻
Thank you!

**Comment by 0b01001110** [comment]
@orlangure 
Sorry for the late reply and thanks for updating.
The latest CircleCI job is [here](https://app.circleci.com/pipelines/github/0b01001110/gnomock/21/workflows/43b59a09-48d3-40c9-91ef-42c0814da13f)

I would be happy if you could check this PR and CircleCI job.

Thanks.

**Pull request merged**
